name: food
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  flutter_map: ^8.0.0
  google_maps_flutter: ^2.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  carousel_slider: ^5.0.0
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  country_picker: ^2.0.27
  flutter_svg: ^2.0.17
  video_player: ^2.0.3
  material_design_icons_flutter: ^7.0.7296
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  image_picker: ^1.1.2
  file_picker: ^9.0.2
  country_code_picker: ^3.0.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  device_apps: ^2.2.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4


  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true
  generate: true

  # Define assets
  assets:
    - assets/
    - assets/restaurantlogo/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter_native_splash:
  color: "#FFFFFF" # Background color
  image: assets/logo4.png # Path to your logo
  android: true
  ios: true
  fullscreen: true # Makes splash screen full screen
