import 'package:food/models.dart';

List<FoodItem> foodItems = [
  FoodItem(
    name: 'Veg Burger',
    categories: [FoodCategory.Veg, FoodCategory.FastFood],
    image: 'assets/burger.png',
    rating: 4.5,
    description: 'A delicious vegetarian burger with fresh veggies.',
    price: 5.99,
    sizeOptions: ['Small', 'Large'],
    addons: ['Pepsi', 'Extra Cheese'],
    allergicIngredients: ['Gluten', 'Dairy'],
    nutritionalDetails: {
      'calories': '350 kcal',
      'carbs': '30g',
      'protein': '12g',
      'fat': '18g',
    },
    restaurantName: 'Burger Heaven',
  ),
  FoodItem(
    name: 'Chicken Wings',
    categories: [FoodCategory.NonVeg, FoodCategory.Grill],
    image: 'assets/chicken_wings.png',
    rating: 4.7,
    description: 'Spicy chicken wings, crispy on the outside and juicy on the inside.',
    price: 7.99,
    sizeOptions: ['Small', 'Large'],
    addons: ['Extra Meat', 'BBQ Sauce'],
    allergicIngredients: ['Gluten', 'Soy'],
    nutritionalDetails: {
      'calories': '400 kcal',
      'carbs': '25g',
      'protein': '20g',
      'fat': '25g',
    },
    restaurantName: 'Grill Master',
  ),
  FoodItem(
    name: 'Sushi',
    categories: [FoodCategory.Asian, FoodCategory.NonVeg],
    image: 'assets/sushi.png',
    rating: 5.0,
    description: 'Fresh sushi made with the finest fish and seaweed.',
    price: 12.99,
    sizeOptions: ['Small', 'Large'],
    addons: ['Soy Sauce', 'Extra Wasabi'],
    allergicIngredients: ['Fish', 'Soy'],
    nutritionalDetails: {
      'calories': '250 kcal',
      'carbs': '30g',
      'protein': '15g',
      'fat': '10g',
    },
    restaurantName: 'Sushi Paradise',
  ),
  FoodItem(
    name: 'Pizza',
    categories: [FoodCategory.Italian, FoodCategory.NonVeg],
    image: 'assets/pizza.png',
    rating: 4.8,
    description: 'A classic Italian pizza with a crispy crust and rich toppings.',
    price: 9.99,
    sizeOptions: ['Medium', 'Large'],
    addons: ['Extra Meat', 'Peppers'],
    allergicIngredients: ['Gluten', 'Dairy'],
    nutritionalDetails: {
      'calories': '800 kcal',
      'carbs': '90g',
      'protein': '30g',
      'fat': '35g',
    },
    restaurantName: 'Pizza Corner',
  ),
  FoodItem(
    name: 'Pasta',
    categories: [FoodCategory.Veg, FoodCategory.Italian],
    image: 'assets/pasta.png',
    rating: 4.6,
    description: 'A rich, creamy pasta with parmesan and basil.',
    price: 6.99,
    sizeOptions: ['Small', 'Large'],
    addons: ['Garlic Bread', 'Extra Sauce'],
    allergicIngredients: ['Gluten', 'Dairy'],
    nutritionalDetails: {
      'calories': '450 kcal',
      'carbs': '60g',
      'protein': '15g',
      'fat': '20g',
    },
    restaurantName: 'Pasta House',
  ),
  FoodItem(
    name: 'Tandoori Chicken',
    categories: [FoodCategory.NonVeg, FoodCategory.Indian],
    image: 'assets/tandoori.png',
    rating: 4.9,
    description: 'Authentic tandoori chicken, marinated with Indian spices.',
    price: 8.99,
    sizeOptions: ['Small', 'Large'],
    addons: ['Raita', 'Naan'],
    allergicIngredients: ['Gluten', 'Dairy'],
    nutritionalDetails: {
      'calories': '500 kcal',
      'carbs': '20g',
      'protein': '35g',
      'fat': '25g',
    },
    restaurantName: 'Spice Hut',
  ),
];
