import 'package:food/models.dart';

class Restaurant {
  final String logo;
  final String name;
  final String image;
  final double rating;
  final List<FoodCategory> categories;
  final List<FoodItem> foodItems;
  final String deliveryTime;
  final double? longitude;
  final double? latitude;

  Restaurant({
    required this.logo,
    required this.name,
    required this.image,
    required this.rating,
    required this.categories,
    required this.foodItems,
    this.deliveryTime = '20-30 minutes',
    this.longitude,
    this.latitude,
  });
}

// Food items list
final Map<String, FoodItem> allFoodItems = {
  'Veg Burger': FoodItem(
    name: 'Veg Burger',
    categories: [FoodCategory.Veg, FoodCategory.FastFood],
    image: 'assets/burger.png',
    rating: 4.5,
    description: "A delicious vegetarian burger with fresh veggies, topped with cheese and served with fries.",
    sizeOptions: ['Small', 'Medium', 'Large'],
    addons: ['Cheese', 'Lettuce', 'Tomato'],
    allergicIngredients: ['Gluten'],
    nutritionalDetails: {'calories': '250', 'carbs': '30g', 'protein': '10g', 'fat': '9g'},
    restaurantName: 'Hungry Puppets',
    price: 15.0,
    discount: 5,
  ),
  'Cake': FoodItem(
    name: 'Cake',
    categories: [FoodCategory.Veg, FoodCategory.MiddleEastern],
    image: 'assets/cake.png',
    rating: 4.5,
    description: "A delicious, creamy cake perfect for dessert lovers.",
    sizeOptions: ['Small', 'Medium', 'Large'],
    addons: ['Chocolate', 'Berries'],
    allergicIngredients: ['Gluten', 'Dairy'],
    nutritionalDetails: {'calories': '300', 'carbs': '40g', 'protein': '5g', 'fat': '12g'},
    restaurantName: 'The Red Cliff Cafe',
    price: 18.0,
    discount: 5,
  ),
  'Pizza': FoodItem(
    name: 'Pizza',
    categories: [FoodCategory.Italian],
    image: 'assets/pizza.png',
    rating: 4.8,
    description: "Classic Italian pizza with crispy crust, tomato sauce, and mozzarella.",
    sizeOptions: ['Small', 'Medium', 'Large'],
    addons: ['Extra Cheese', 'Olives'],
    allergicIngredients: ['Gluten', 'Dairy'],
    nutritionalDetails: {'calories': '300', 'carbs': '35g', 'protein': '15g', 'fat': '12g'},
    restaurantName: 'Red Cliff Cafe',
    price: 20.0,
  ),
  'Chicken Wings': FoodItem(
    name: 'Chicken Wings',
    categories: [FoodCategory.NonVeg, FoodCategory.Grill],
    image: 'assets/chicken_wings.png',
    rating: 4.7,
    description: "Crispy chicken wings seasoned with BBQ sauce.",
    sizeOptions: ['6 pcs', '12 pcs'],
    addons: ['BBQ Sauce', 'Buffalo Sauce'],
    allergicIngredients: ['Dairy'],
    nutritionalDetails: {'calories': '400', 'carbs': '10g', 'protein': '35g', 'fat': '20g'},
    restaurantName: 'Food Street',
    price: 18.0,
    discount: 10,
  ),
  'Tandoori Chicken': FoodItem(
    name: 'Tandoori Chicken',
    categories: [FoodCategory.NonVeg, FoodCategory.Grill],
    image: 'assets/tandoori.png',
    rating: 4.9,
    description: "Authentic Indian-style tandoori chicken, marinated with yogurt and spices.",
    sizeOptions: ['Half', 'Full'],
    addons: ['Mint Chutney', 'Onions'],
    allergicIngredients: [],
    nutritionalDetails: {'calories': '320', 'carbs': '5g', 'protein': '40g', 'fat': '12g'},
    restaurantName: 'The Capital Grill',
    price: 22.0,
  ),
  'Biryani': FoodItem(
    name: 'Biryani',
    categories: [FoodCategory.Asian, FoodCategory.NonVeg],
    image: 'assets/biryani.png',
    rating: 4.6,
    description: "Fragrant basmati rice cooked with aromatic spices and tender meat.",
    sizeOptions: ['Small', 'Medium', 'Large'],
    addons: ['Raita', 'Boiled Egg'],
    allergicIngredients: ['Dairy'],
    nutritionalDetails: {'calories': '450', 'carbs': '50g', 'protein': '30g', 'fat': '15g'},
    restaurantName: 'Tasty Takeaways',
    price: 17.0,
  ),
  'Sushi': FoodItem(
    name: 'Sushi',
    categories: [FoodCategory.Asian, FoodCategory.NonVeg],
    image: 'assets/sushi.png',
    rating: 4.8,
    description: "Delicate sushi rolls with fresh fish and rice.",
    sizeOptions: ['6 pcs', '12 pcs'],
    addons: ['Wasabi', 'Soy Sauce'],
    allergicIngredients: ['Seafood'],
    nutritionalDetails: {'calories': '250', 'carbs': '45g', 'protein': '20g', 'fat': '5g'},
    restaurantName: 'The Red Cliff Cafe',
    price: 25.0,
  ),
};


final List<Restaurant> restaurants = [
  Restaurant(
    name: "Café Monarch",
    image: "assets/cafemonarch.png",
    rating: 5.0,
    categories: [FoodCategory.Veg, FoodCategory.Asian],
    foodItems: [
      allFoodItems['Veg Burger']!,
      allFoodItems['Pizza']!,
      allFoodItems['Biryani']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Chicken Wings']!,
    ], logo: 'assets/restaurantlogo/cafemonarchlogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 27.7200,
    longitude: 85.3300,
  ),
  Restaurant(
    name: "The Capital Grill",
    image: "assets/capitalgrill.png",
    rating: 5.0,
    categories: [FoodCategory.NonVeg, FoodCategory.Grill],
    foodItems: [
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Chicken Wings']!,
      allFoodItems['Pizza']!,
      allFoodItems['Biryani']!,
      allFoodItems['Veg Burger']!,
      allFoodItems['Cake']!,
    ], logo: 'assets/restaurantlogo/thecapitalgrill.png',
    deliveryTime: '20-30 minutes',
    latitude: 27.7172,
    longitude: 85.3240,
  ),
  Restaurant(
    name: "Tasty Takeaways",
    image: "assets/tastytakeaways.png",
    rating: 4.9,
    categories: [FoodCategory.Asian],
    foodItems: [
      allFoodItems['Biryani']!,
      allFoodItems['Pizza']!,
      allFoodItems['Sushi']!,
      allFoodItems['Cake']!,
      allFoodItems['Chicken Wings']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Veg Burger']!,
    ],
    logo: 'assets/restaurantlogo/tastytakeawayslogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 27.7225,
    longitude: 85.3287,
  ),
  Restaurant(
    name: "Red Cliff Cafe",
    image: "assets/redcliffcafe.png",
    rating: 4.7,
    categories: [FoodCategory.Italian],
    foodItems: [
      allFoodItems['Pizza']!,
      allFoodItems['Cake']!,
      allFoodItems['Veg Burger']!,
      allFoodItems['Sushi']!,
      allFoodItems['Chicken Wings']!,
      allFoodItems['Biryani']!,
      allFoodItems['Tandoori Chicken']!,
    ],logo: 'assets/restaurantlogo/redcliffcafelogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 27.7153,
    longitude: 85.3202,
  ),
  Restaurant(
    name: "Hungry Puppets",
    image: "assets/hungrypuppets.png",
    rating: 4.7,
    categories: [FoodCategory.FastFood],
    foodItems: [
      allFoodItems['Veg Burger']!,
      allFoodItems['Chicken Wings']!,
      allFoodItems['Pizza']!,
      allFoodItems['Cake']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Biryani']!,
      allFoodItems['Sushi']!,
    ],logo: 'assets/restaurantlogo/hungrypuppetslogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 27.7189,
    longitude: 85.3225,
  ),
  // Additional restaurants
  Restaurant(
    name: "The Royal Dine",
    image: "assets/restaurant.png",
    rating: 4.8,
    categories: [FoodCategory.Veg, FoodCategory.Italian],
    foodItems: [
      allFoodItems['Pizza']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Biryani']!,
      allFoodItems['Sushi']!,
      allFoodItems['Veg Burger']!,
    ],logo: 'assets/restaurantlogo/theroyaldinelogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 27.7211,
    longitude: 85.3258,
  ),
  Restaurant(
    name: "Food Street",
    image: "assets/restaurant.png",
    rating: 4.6,
    categories: [FoodCategory.FastFood, FoodCategory.Veg],
    foodItems: [
      allFoodItems['Veg Burger']!,
      allFoodItems['Pizza']!,
      allFoodItems['Sushi']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Biryani']!,
    ],logo: 'assets/restaurantlogo/foodstreetlogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 27.7195,
    longitude: 85.3273,
  ),
  Restaurant(
    name: "Spicy Delights",
    image: "assets/spicydelights.png",
    rating: 4.5,
    categories: [FoodCategory.NonVeg, FoodCategory.Asian],
    foodItems: [
      allFoodItems['Biryani']!,
      allFoodItems['Chicken Wings']!,
      allFoodItems['Sushi']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Veg Burger']!,
    ],logo: 'assets/restaurantlogo/spicydelightlogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 27.7231,
    longitude: 85.3295,
  ),
  Restaurant(
    name: "Bistro 360",
    image: "assets/bistro360.png",
    rating: 4.8,
    categories: [FoodCategory.Italian, FoodCategory.Grill],
    foodItems: [
      allFoodItems['Pizza']!,
      allFoodItems['Cake']!,
      allFoodItems['Chicken Wings']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Biryani']!,
    ],logo: 'assets/restaurantlogo/bistro360logo.png',
    deliveryTime: '20-30 minutes',
    latitude: 28.7231,
    longitude: 86.3295,
  ),
  Restaurant(
    name: "Fusion Feast",
    image: "assets/fusionfeast.png",
    rating: 4.7,
    categories: [FoodCategory.NonVeg, FoodCategory.FastFood],
    foodItems: [
      allFoodItems['Chicken Wings']!,
      allFoodItems['Veg Burger']!,
      allFoodItems['Pizza']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Sushi']!,
    ],logo: 'assets/restaurantlogo/fusionfeastlogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 29.7231,
    longitude: 86.3295,
  ),
  Restaurant(
    name: "Ocean Breeze",
    image: "assets/oceanbreeze.png",
    rating: 4.6,
    categories: [FoodCategory.Asian],
    foodItems: [
      allFoodItems['Sushi']!,
      allFoodItems['Biryani']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Pizza']!,
      allFoodItems['Veg Burger']!,
    ],logo: 'assets/restaurantlogo/oceanbreezelogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 25.7231,
    longitude: 86.3295,
  ),
  Restaurant(
    name: "The Greenhouse",
    image: "assets/greenhouse.png",
    rating: 4.5,
    categories: [FoodCategory.Veg],
    foodItems: [
      allFoodItems['Veg Burger']!,
      allFoodItems['Biryani']!,
      allFoodItems['Pizza']!,
      allFoodItems['Cake']!,
      allFoodItems['Tandoori Chicken']!,
    ],logo: 'assets/restaurantlogo/greenhouselogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 20.7231,
    longitude: 86.3295,
  ),
  Restaurant(
    name: "Sizzle Town",
    image: "assets/sizzletown.png",
    rating: 4.8,
    categories: [FoodCategory.Grill, FoodCategory.FastFood],
    foodItems: [
      allFoodItems['Chicken Wings']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Biryani']!,
      allFoodItems['Pizza']!,
      allFoodItems['Cake']!,
    ], logo: 'assets/restaurantlogo/sizzletownlogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 38.7231,
    longitude: 86.3295,
  ),
  Restaurant(
    name: "Pizza Place",
    image: "assets/pizzaplace.png",
    rating: 4.9,
    categories: [FoodCategory.Italian],
    foodItems: [
      allFoodItems['Pizza']!,
      allFoodItems['Cake']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Biryani']!,
      allFoodItems['Chicken Wings']!,
    ], logo: 'assets/restaurantlogo/pizzaplacelogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 28.7231,
    longitude: 76.3295,
  ),
  Restaurant(
    name: "Healthy Eats",
    image: "assets/healthyyeats.png",
    rating: 4.6,
    categories: [FoodCategory.Veg],
    foodItems: [
      allFoodItems['Veg Burger']!,
      allFoodItems['Sushi']!,
      allFoodItems['Biryani']!,
      allFoodItems['Pizza']!,
      allFoodItems['Cake']!,
    ], logo: 'assets/restaurantlogo/healthyeatslogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 28.7231,
    longitude: 88.3295,
  ),
  Restaurant(
    name: "Burger Haven",
    image: "assets/burgerhaven.png",
    rating: 4.7,
    categories: [FoodCategory.FastFood],
    foodItems: [
      allFoodItems['Veg Burger']!,
      allFoodItems['Pizza']!,
      allFoodItems['Chicken Wings']!,
      allFoodItems['Tandoori Chicken']!,
      allFoodItems['Biryani']!,
    ], logo: 'assets/restaurantlogo/burgerhavenlogo.png',
    deliveryTime: '20-30 minutes',
    latitude: 28.7231,
    longitude: 89.3295,
  ),
];

// Carousel images
final List<String> carouselImages = [
  'assets/burger.png',
  'assets/tandoori.png',
  'assets/cake.png',
  'assets/pizza.png',
  'assets/chicken_wings.png',
];
